
//! Autogenerated weights for `pallet_kitty`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-07-28, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_kitty
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_kitty`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_kitty::WeightInfo for WeightInfo<T> {
	// Storage: Kitty KittyOwner (r:1 w:1)
	// Storage: Kitty Nonce (r:1 w:1)
	// Storage: RandomnessCollectiveFlip RandomMaterial (r:1 w:0)
	// Storage: Kitty KittyNumber (r:1 w:1)
	// Storage: Timestamp Now (r:1 w:0)
	// Storage: Kitty Kitty (r:0 w:1)
	fn create_kitty() -> Weight {
		(50_700_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(5 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: Kitty Kitty (r:1 w:0)
	// Storage: Kitty KittyOwner (r:2 w:2)
	fn change_owner() -> Weight {
		(21_900_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(3 as Weight))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
	}
}
